services:
  api:
    image: ag-go-api:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    mem_limit: ${API_MEMORY_LIMIT:-2g}
    cpus: ${API_CPUS:-2}
    deploy:
      resources:
        limits:
          cpus: '${API_CPUS:-2}'
          memory: ${API_MEMORY_LIMIT:-2g}
    restart: unless-stopped

  worker:
    image: ag-go-api:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    command: ['node', 'dist/workers/worker.js']
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    mem_limit: ${WORKER_MEMORY_LIMIT:-2g}
    cpus: ${WORKER_CPUS:-2}
    deploy:
      resources:
        limits:
          cpus: '${WORKER_CPUS:-2}'
          memory: ${WORKER_MEMORY_LIMIT:-2g}
    restart: unless-stopped
